services:
  - type: web
    name: f1-colapinto-json
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
